/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankteller;

import org.checkerframework.checker.units.qual.A;

public class App {

    public static void main(String[] args) {
        Bank bank = new Bank();
        Account checkings = new Account("2342", "checkings", 34039535);
        Account savings = new Account("2324", "savings", 23242);
        bank.openNewAccount(checkings.getAccountNumber(), checkings);
        bank.openNewAccount(savings.getAccountNumber(), savings);
    }
}
